# .streamlit/secrets.toml

# Streamlitのデプロイ時に必要な外部DB接続情報
# 以下の [YOUR-CONNECTION-URL] に、Supabaseで取得した接続文字列を貼り付けてください。
# 例: postgresql://postgres:mypassword@abcdefghijkl.supabase.co:5432/postgres

DATABASE_URL = "postgresql://postgres:0savlaNclis@db.svrrqebpaajuixeplqbl.supabase.co:5432/postgres" 

# このエントリは、Streamlit Cloudがsecretsファイルを見つけるために必要です。
[general]
project_url = "[PROJECT_URL]"
